// Generated TypeScript types from DBML schema
// This file is auto-generated from schema.dbml using the official @dbml/core parser
// Do not edit this file directly - edit schema.dbml instead

export interface TodoType {
  id: number;
  title: string;
  due_date?: string | null;
  done_flag: boolean;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}
export interface AuditLogType {
  id: number;
  todo_id: number;
  action: string;
  old_values?: string | null;
  new_values?: string | null;
  created_at: string;
}
export interface UserType {
  user_id: string;
  name: string;
  email: string;
  position?: string | null;
  photo_url?: string | null;
  created_at: string;
  updated_at: string;
}
export interface UserAppType {
  id: number;
  user_id: string;
  app_name: string;
  created_at: string;
}
export interface UserRoleType {
  id: number;
  user_id: string;
  app_name: string;
  role: string;
  created_at: string;
}
export interface TeamStructurePageType {
  id: number;
  page_name: string;
  description?: string | null;
  is_active: boolean;
  chart_data: Record<string, any>;
  created_at: string;
  updated_at: string;
}

// CRUD Operation Types
export interface CreateTodoType {
  title: string;
  due_date?: string | null;
  done_flag?: boolean | null;
  created_at?: string | null;
  updated_at?: string | null;
  deleted_at?: string | null;
}
export interface UpdateTodoType {
  id: number;
  title?: string | null;
  due_date?: string | null;
  done_flag?: boolean | null;
  created_at?: string | null;
  updated_at?: string | null;
  deleted_at?: string | null;
}
export interface CreateAuditLogType {
  todo_id: number;
  action: string;
  old_values?: string | null;
  new_values?: string | null;
  created_at?: string | null;
}
export interface UpdateAuditLogType {
  id: number;
  todo_id?: number | null;
  action?: string | null;
  old_values?: string | null;
  new_values?: string | null;
  created_at?: string | null;
}
export interface CreateUserType {
  name: string;
  email: string;
  position?: string | null;
  photo_url?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface UpdateUserType {
  user_id: string;
  name?: string | null;
  email?: string | null;
  position?: string | null;
  photo_url?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface CreateUserAppType {
  user_id: string;
  app_name: string;
  created_at?: string | null;
}
export interface UpdateUserAppType {
  id: number;
  user_id?: string | null;
  app_name?: string | null;
  created_at?: string | null;
}
export interface CreateUserRoleType {
  user_id: string;
  app_name: string;
  role: string;
  created_at?: string | null;
}
export interface UpdateUserRoleType {
  id: number;
  user_id?: string | null;
  app_name?: string | null;
  role?: string | null;
  created_at?: string | null;
}
export interface CreateTeamStructurePageType {
  page_name: string;
  description?: string | null;
  is_active?: boolean | null;
  chart_data?: Record<string, any> | null;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface UpdateTeamStructurePageType {
  id: number;
  page_name?: string | null;
  description?: string | null;
  is_active?: boolean | null;
  chart_data?: Record<string, any> | null;
  created_at?: string | null;
  updated_at?: string | null;
}

// Basic type aliases for compatibility
export type Todo = TodoType;
export type NewTodo = CreateTodoType;
export type AuditLog = AuditLogType;
export type NewAuditLog = CreateAuditLogType;
export type User = UserType;
export type NewUser = CreateUserType;
export type UserApp = UserAppType;
export type NewUserApp = CreateUserAppType;
export type UserRole = UserRoleType;
export type NewUserRole = CreateUserRoleType;
export type TeamStructurePage = TeamStructurePageType;
export type NewTeamStructurePage = CreateTeamStructurePageType;
