-- Insert 30 realistic dummy users
INSERT INTO "public"."users" ("user_id", "name", "email", "created_at", "updated_at") VALUES
('john.doe', 'John Doe', 'john.doe@company.com', NOW(), NOW()),
('jane.smith', 'Jane Smith', 'jane.smith@company.com', NOW(), NOW()),
('michael.johnson', 'Michael Johnson', 'michael.johnson@company.com', NOW(), NOW()),
('sarah.williams', 'Sarah Williams', 'sarah.williams@company.com', NOW(), NOW()),
('david.brown', 'David Brown', 'david.brown@company.com', NOW(), NOW()),
('emily.davis', 'Emily Davis', 'emily.davis@company.com', NOW(), NOW()),
('robert.miller', 'Robert Miller', 'robert.miller@company.com', NOW(), NOW()),
('lisa.wilson', 'Lisa Wilson', 'lisa.wilson@company.com', NOW(), NOW()),
('james.moore', 'James Moore', 'james.moore@company.com', NOW(), NOW()),
('amanda.taylor', 'Amanda Taylor', 'amanda.taylor@company.com', NOW(), NOW()),
('christopher.anderson', 'Christopher Anderson', 'christopher.anderson@company.com', NOW(), NOW()),
('michelle.thomas', 'Michelle Thomas', 'michelle.thomas@company.com', NOW(), NOW()),
('matthew.jackson', 'Matthew Jackson', 'matthew.jackson@company.com', NOW(), NOW()),
('jennifer.white', 'Jennifer White', 'jennifer.white@company.com', NOW(), NOW()),
('daniel.harris', 'Daniel Harris', 'daniel.harris@company.com', NOW(), NOW()),
('ashley.martin', 'Ashley Martin', 'ashley.martin@company.com', NOW(), NOW()),
('andrew.garcia', 'Andrew Garcia', 'andrew.garcia@company.com', NOW(), NOW()),
('jessica.rodriguez', 'Jessica Rodriguez', 'jessica.rodriguez@company.com', NOW(), NOW()),
('joshua.lewis', 'Joshua Lewis', 'joshua.lewis@company.com', NOW(), NOW()),
('stephanie.lee', 'Stephanie Lee', 'stephanie.lee@company.com', NOW(), NOW()),
('kevin.walker', 'Kevin Walker', 'kevin.walker@company.com', NOW(), NOW()),
('rachel.hall', 'Rachel Hall', 'rachel.hall@company.com', NOW(), NOW()),
('brandon.allen', 'Brandon Allen', 'brandon.allen@company.com', NOW(), NOW()),
('nicole.young', 'Nicole Young', 'nicole.young@company.com', NOW(), NOW()),
('ryan.hernandez', 'Ryan Hernandez', 'ryan.hernandez@company.com', NOW(), NOW()),
('megan.king', 'Megan King', 'megan.king@company.com', NOW(), NOW()),
('tyler.wright', 'Tyler Wright', 'tyler.wright@company.com', NOW(), NOW()),
('lauren.lopez', 'Lauren Lopez', 'lauren.lopez@company.com', NOW(), NOW()),
('justin.hill', 'Justin Hill', 'justin.hill@company.com', NOW(), NOW()),
('kimberly.scott', 'Kimberly Scott', 'kimberly.scott@company.com', NOW(), NOW())
ON CONFLICT ("user_id") DO NOTHING;

-- Insert user app assignments
INSERT INTO "public"."user_apps" ("user_id", "app_name", "created_at") VALUES
-- User Manager App assignments
('john.doe', 'usermanager', NOW()),
('jane.smith', 'usermanager', NOW()),
('michael.johnson', 'usermanager', NOW()),
('sarah.williams', 'usermanager', NOW()),
('david.brown', 'usermanager', NOW()),
('emily.davis', 'usermanager', NOW()),
('robert.miller', 'usermanager', NOW()),
('lisa.wilson', 'usermanager', NOW()),
('james.moore', 'usermanager', NOW()),
('amanda.taylor', 'usermanager', NOW()),
('christopher.anderson', 'usermanager', NOW()),
('michelle.thomas', 'usermanager', NOW()),
('matthew.jackson', 'usermanager', NOW()),
('jennifer.white', 'usermanager', NOW()),
('daniel.harris', 'usermanager', NOW()),
-- Quote App assignments
('john.doe', 'quoteapp', NOW()),
('jane.smith', 'quoteapp', NOW()),
('michael.johnson', 'quoteapp', NOW()),
('sarah.williams', 'quoteapp', NOW()),
('ashley.martin', 'quoteapp', NOW()),
('andrew.garcia', 'quoteapp', NOW()),
('jessica.rodriguez', 'quoteapp', NOW()),
('joshua.lewis', 'quoteapp', NOW()),
('stephanie.lee', 'quoteapp', NOW()),
('kevin.walker', 'quoteapp', NOW()),
('rachel.hall', 'quoteapp', NOW()),
('brandon.allen', 'quoteapp', NOW()),
('nicole.young', 'quoteapp', NOW()),
('ryan.hernandez', 'quoteapp', NOW()),
('megan.king', 'quoteapp', NOW()),
('tyler.wright', 'quoteapp', NOW()),
('lauren.lopez', 'quoteapp', NOW()),
('justin.hill', 'quoteapp', NOW()),
('kimberly.scott', 'quoteapp', NOW())
ON CONFLICT ("user_id", "app_name") DO NOTHING;

-- Insert user role assignments
INSERT INTO "public"."user_roles" ("user_id", "app_name", "role", "created_at") VALUES
-- User Manager roles
('john.doe', 'usermanager', 'usermanager-admin', NOW()),
('jane.smith', 'usermanager', 'usermanager-admin', NOW()),
('michael.johnson', 'usermanager', 'usermanager-approver', NOW()),
('sarah.williams', 'usermanager', 'usermanager-approver', NOW()),
('david.brown', 'usermanager', 'usermanager-approver', NOW()),
('emily.davis', 'usermanager', 'usermanager-viewer', NOW()),
('robert.miller', 'usermanager', 'usermanager-viewer', NOW()),
('lisa.wilson', 'usermanager', 'usermanager-viewer', NOW()),
('james.moore', 'usermanager', 'usermanager-editor', NOW()),
('amanda.taylor', 'usermanager', 'usermanager-editor', NOW()),
('christopher.anderson', 'usermanager', 'usermanager-editor', NOW()),
('michelle.thomas', 'usermanager', 'usermanager-approver', NOW()),
('matthew.jackson', 'usermanager', 'usermanager-viewer', NOW()),
('jennifer.white', 'usermanager', 'usermanager-editor', NOW()),
('daniel.harris', 'usermanager', 'usermanager-admin', NOW()),
-- Quote App roles
('john.doe', 'quoteapp', 'quoteapp-sales', NOW()),
('jane.smith', 'quoteapp', 'quoteapp-trader', NOW()),
('michael.johnson', 'quoteapp', 'quoteapp-manager', NOW()),
('sarah.williams', 'quoteapp', 'quoteapp-sales', NOW()),
('ashley.martin', 'quoteapp', 'quoteapp-trader', NOW()),
('andrew.garcia', 'quoteapp', 'quoteapp-trader', NOW()),
('jessica.rodriguez', 'quoteapp', 'quoteapp-sales', NOW()),
('joshua.lewis', 'quoteapp', 'quoteapp-sales', NOW()),
('stephanie.lee', 'quoteapp', 'quoteapp-analyst', NOW()),
('kevin.walker', 'quoteapp', 'quoteapp-analyst', NOW()),
('rachel.hall', 'quoteapp', 'quoteapp-manager', NOW()),
('brandon.allen', 'quoteapp', 'quoteapp-trader', NOW()),
('nicole.young', 'quoteapp', 'quoteapp-sales', NOW()),
('ryan.hernandez', 'quoteapp', 'quoteapp-analyst', NOW()),
('megan.king', 'quoteapp', 'quoteapp-manager', NOW()),
('tyler.wright', 'quoteapp', 'quoteapp-sales', NOW()),
('lauren.lopez', 'quoteapp', 'quoteapp-analyst', NOW()),
('justin.hill', 'quoteapp', 'quoteapp-trader', NOW()),
('kimberly.scott', 'quoteapp', 'quoteapp-sales', NOW())
ON CONFLICT ("user_id", "app_name", "role") DO NOTHING;